name: Format Dart Code

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: flutter format --line-length 200 lib/ test/ example/

      - name: Check for changes
        run: |
          git diff --exit-code || (echo "::error::Code formatting issues found. Run 'flutter format --line-length 200 lib/ test/ example/' to fix." && exit 1)
